Adding label functionality.
github/codescanning-jira-integration pull request #15
Opened 2021-08-13 00:05 UTC by zacharyr-qb

Adds the functionality to be able to add labels to newly created Jira bugs. 

A user can add
```
with:
    jira_label: 'red-team,GreenTeam,blueteam'
```
to their GitHub -> Jira workflows to have those labels added to the Jira bugs.

2021-08-18 01:45 UTC, cmboling commented on action.yml
> +    description: 'JIRA bug label(s). Value format "red-team,blue-team,GreenTeam", or "red-team"
```suggestion
    description: 'JIRA bug label(s). (e.g. value format can be "red-team,blue-team,GreenTeam", or "red-team")
```

2021-08-19 04:53 UTC, cmboling commented
I think we've briefly touched on this today, but as mentioned in your comment this is good for new alerts at this point. Existing open Jira issues won't have this new label. Is that something that you'd want? Also if the `jira_label` changes within the workflow, would you want all issues to adhere to the new label that will be synced? I believe this will involve passing the label to `sync.py` as well as `serve.py` Not sure how many other folks are using _serve_ but let's stick to _sync_ since that's seems to be the most commonly used feature.

2021-08-19 13:54 UTC, zacharyr-qb commented
> I think we've briefly touched on this today, but as mentioned in your comment this is good for new alerts at this point. Existing open Jira issues won't have this new label. Is that something that you'd want? 

I think it would be most intuitive if we update existing Jira issues with the new labels that have been entered into the workflow.

> Also if the `jira_label` changes within the workflow, would you want all issues to adhere to the new label that will be synced? 

I think this also is in line with the previous question. I think it would definitely be best for us to have all issues (that have been created, or will be created) by the workflow to be aligned with the labels defined in the workflow.

2021-09-03 00:18 UTC, cmboling commented
@zacharyr-qb will you smoke test the changes and let me know how it goes?

2021-10-05 17:32 UTC, zacharyr-qb commented
Done! All the functionality works great!

2021-10-11 22:26 UTC, merged

2024-09-18 20:47 UTC, Henko551 approved these changes

2024-09-18 20:47 UTC, Henko551 requested changes
- [ ] -